### PR TITLE
Fixed Date description

### PR DESCRIPTION
**Pull request by stefanak-michal**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-bolt-24.surge.sh

**Review by robsdedude — APPROVED** [review]
:calendar:

**Review by fbiville — APPROVED** [review]

**Comment by fbiville** [comment]
Semi-related to this PR: shouldn't we remove "table 2" from https://neo4j.com/docs/bolt/current/packstream/?
We moved all specific structure to Bolt, but this table remains in Packstream for some reason.

**Comment by fbiville** [comment]
Alright, let me do that now.

**Pull request merged**
